[GH-18] Add first version of service contract
iu7og/bongodb pull request #19
Opened 2022-03-20 16:49 UTC by hackfeed

* Add first version of proto for client-server communication

2022-03-20 16:55 UTC, mRrvz requested changes

2022-03-20 16:55 UTC, mRrvz commented on proto/bongodb.proto
> +}
не хватает пустой строки!

2022-03-20 16:55 UTC, mRrvz commented on proto/bongodb.proto
> +    int32 code = 1;
мб int32 -> uint32?

2022-03-21 06:19 UTC, Justarone requested changes

2022-03-21 06:19 UTC, Justarone commented on proto/bongodb.proto
> +message Empty {
1. не очень понятно, зачем это нужно (либо переименуй, либо оставь коммент)
2. для логов, обсудили голосом, что можно добавить аргумент для сбора логов (офсет, чтобы не все собирать каждый раз, например)

2022-03-21 06:19 UTC, Justarone commented on proto/bongodb.proto
> +  rpc Truncate(Empty) returns (ErrorResponse) {}
Не очень понятно, что имеется в виду

2022-03-21 06:19 UTC, Justarone commented on proto/bongodb.proto
> +  rpc GetLogs(Empty) returns (LogsResponse)  {}
может разделить на несколько сервисов? кажется, это относится к инфре, а не к дб, и не будет реализовано на стороне с++, разве нет?

2022-03-21 06:19 UTC, Justarone commented on proto/bongodb.proto
> +  string key = 1;
решили делать без других видов ключей? (фиксированной длины, целочисленных и тд)

2022-03-21 06:19 UTC, Justarone commented on proto/bongodb.proto
> +message ErrorResponse {
если следующий ответ - ValueResponse, то может это должно быть EmptyResponse?

2022-03-21 06:19 UTC, Justarone commented on proto/bongodb.proto
> +  string key = 1;
ваще если мы захотим несколько ключей, можно будет заюзать [oneof](https://developers.google.com/protocol-buffers/docs/proto3#oneof)

2022-03-21 06:19 UTC, Justarone commented on proto/bongodb.proto
> +  string level = 2;
точно ли это должно быть строкой? может быть uint32?

2022-03-21 06:19 UTC, Justarone commented on proto/bongodb.proto
> +  google.protobuf.Timestamp timestamp = 1;
хайпова кстати, я бы просто чиселку взял..

2022-03-23 19:05 UTC, hackfeed commented on proto/bongodb.proto
> +  rpc Truncate(Empty) returns (ErrorResponse) {}
Удаление всех ключей разом

2022-03-23 19:05 UTC, hackfeed commented on proto/bongodb.proto
> +message Empty {
Для логов по итогу не будет никакого вызова, утилита сама будет лезть в файлы и вычитывать их

2022-03-23 19:05 UTC, hackfeed commented on proto/bongodb.proto
> +    int32 code = 1;
Поправлено

2022-03-23 19:05 UTC, hackfeed commented on proto/bongodb.proto
> +}
Добавил братанчик

2022-03-23 19:06 UTC, hackfeed commented on proto/bongodb.proto
> +  rpc GetLogs(Empty) returns (LogsResponse)  {}
Логов не будет вовсе

2022-03-23 19:06 UTC, hackfeed commented on proto/bongodb.proto
> +  string key = 1;
Давайте для простоты остановимся на строке

2022-03-23 19:06 UTC, hackfeed commented on proto/bongodb.proto
> +message ErrorResponse {
Сделаю NoValueResponse

2022-03-23 19:06 UTC, hackfeed commented on proto/bongodb.proto
> +  string level = 2;
Логов не будет

2022-03-23 19:07 UTC, hackfeed commented on proto/bongodb.proto
> +  google.protobuf.Timestamp timestamp = 1;
Логов не будет

2022-03-23 20:33 UTC, Justarone commented on .gitignore
> +!go.mod
Может просто mod убрать? Фортрана не будет, гарантирую.

2022-03-23 20:33 UTC, Justarone commented on bongocli/go.sum
> +cloud.google.com/go v0.26.0/go.mod h1:aQUYkXzVsufM+DwF1aE+0xfcU+56JwCaLick0ClmMTw=
Просто что-то много и не очень понятно, зочем

2022-03-23 20:33 UTC, Justarone commented on bongodb/bongodb.proto
> +  google.protobuf.StringValue key = 1;
[здесь и далее] а чем не устроило обычное описание типов? bytes, uint32, etc

2022-03-23 20:36 UTC, hackfeed commented on .gitignore
> +!go.mod
Уберем

2022-03-23 20:37 UTC, hackfeed commented on bongocli/cmd/bongocli/main.go
> +	conn, err := grpc.Dial(addr, grpc.WithTransportCredentials(insecure.NewCredentials()))
Объект подключения, не очень понял, о чем вопрос

2022-03-23 20:37 UTC, hackfeed commented on bongocli/go.sum
> +cloud.google.com/go v0.26.0/go.mod h1:aQUYkXzVsufM+DwF1aE+0xfcU+56JwCaLick0ClmMTw=
go.sum обязательно должен быть в репе вместе с go.mod

2022-03-23 20:38 UTC, hackfeed commented on bongodb/bongodb.proto
> +  google.protobuf.StringValue key = 1;
В Go если поле не приходит, то оно заполняется пустым значением. Грубо говоря, если я захочу намеренно отдать false, не будет понятно, я намеренно отдал false или просто не передал значение. Такие обертки nullable, поэтому тут неопределённости не будет. Для перестраховки

2022-03-23 20:39 UTC, hackfeed commented on bongodb/bongodb.proto
> +  google.protobuf.UInt32Value code = 1;
Ошибка вообще выпялится, так как grpc по дефолту отдает ошибку и ее можно кастомизировать. Сейчас залью новую версию

2022-03-23 20:40 UTC, mRrvz commented on .gitignore
> +!go.mod
на фортране будем писать математические библиотеки

2022-03-23 20:43 UTC, hackfeed commented on bongocli/cmd/bongocli/main.go
> +	defer conn.Close()
Точно

2022-03-23 20:43 UTC, mRrvz commented on bongocli/go.sum
> +cloud.google.com/go v0.26.0/go.mod h1:aQUYkXzVsufM+DwF1aE+0xfcU+56JwCaLick0ClmMTw=
все правильно так надо

2022-03-23 20:43 UTC, Justarone commented on bongocli/cmd/bongocli/main.go
> +	conn, err := grpc.Dial(addr, grpc.WithTransportCredentials(insecure.NewCredentials()))
Вопрос про режимы работы или что-то вроде того (https://grpc.io/docs/what-is-grpc/core-concepts/#overview) + у Лехи куча экзотики было, надо как-то согласованно этот момент проделать, что и как мы используем

2022-03-23 20:44 UTC, mRrvz commented on bongocli/internal/pb/bongodb/bongodb.pb.go
> +// Code generated by protoc-gen-go. DO NOT EDIT.
это весь файл сгенеренный? тогда нет смысла его в репу лить

2022-03-23 20:44 UTC, mRrvz commented on bongocli/internal/pb/bongodb/bongodb_grpc.pb.go
> +// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
аналогично

2022-03-23 20:44 UTC, mRrvz commented on bongodb/bongodb.proto
> +option go_package = "github.com/iu7og/bongodb/bongodb";
флекс не видел такого .. флексишь братишка!

2022-03-23 20:45 UTC, mRrvz commented on bongodb/bongodb.proto
> +option go_package = "github.com/iu7og/bongodb/bongodb";
а это не го))

2022-03-23 20:46 UTC, hackfeed commented on bongocli/internal/pb/bongodb/bongodb.pb.go
> +// Code generated by protoc-gen-go. DO NOT EDIT.
Я не могу обращаться к интерфейсу если этого интерфейса нет. Как я тебе его лить не буду?

2022-03-23 20:47 UTC, Justarone commented on bongodb/bongodb.proto
> +  google.protobuf.StringValue key = 1;
"намеренно отдать false" - так ты вроде берешь, а на отдаешь, не?

2022-03-23 20:48 UTC, Justarone commented on bongodb/bongodb.proto
> +  google.protobuf.StringValue key = 1;
или ты планируешь, что приложение будет еще что-то вроде централизованного клиента, на который обращаются, а он руками шардирует? (мб я не допонял чета)

2022-03-23 20:48 UTC, Justarone commented on bongodb/bongodb.proto
> +  google.protobuf.UInt32Value code = 1;
закрой тред, как сделаешь

2022-03-23 20:51 UTC, hackfeed commented on bongodb/bongodb.proto
> +  google.protobuf.StringValue key = 1;
Если с сервера отдать пустую строчку, или false, или 0 в интовое поле, клиент не будет понимать - дефолтное это значение или намеренно отданное

2022-03-23 20:51 UTC, hackfeed commented on bongocli/cmd/bongocli/main.go
> +	conn, err := grpc.Dial(addr, grpc.WithTransportCredentials(insecure.NewCredentials()))
Мы вроде как обсуждали, что без стримов, самые обычные коллы

2022-03-24 05:13 UTC, Justarone commented on bongocli/internal/pb/bongodb/bongodb.pb.go
> +// Code generated by protoc-gen-go. DO NOT EDIT.
Все верно, это должно быть первым шагом сборки, чтобы при сборке го интерфейс уже был.

2022-03-24 07:30 UTC, hackfeed commented on bongocli/internal/pb/bongodb/bongodb.pb.go
> +// Code generated by protoc-gen-go. DO NOT EDIT.
Если сгенеренных прото не будет в репозитории, линт и билд в CI не будут проходить

2022-03-24 08:33 UTC, Justarone approved these changes
Я бы ещё с Мишей бы обсудил сгенерированный код в репе

2022-03-24 08:37 UTC, hackfeed commented
> Я бы ещё с Мишей бы обсудил сгенерированный код в репе

> Если сгенеренных прото не будет в репозитории, линт и билд в CI не будут проходить

По-моему все понятно, зачем они нужны, нет?

2022-03-24 16:38 UTC, mRrvz commented on .github/workflows/linter.yml
> +      - master
по хорошему, это должен быть отдельный коммит

2022-03-24 16:39 UTC, mRrvz commented on bongocli/Makefile
> +	rm -rf bin/*.exe
тут -r не нужен

2022-03-24 17:04 UTC, mRrvz commented
Так как мы не делаем squash в один коммит при мерджом, я бы вынес изменения gitignore, linter в другие коммиты.

2022-03-24 18:07 UTC, hackfeed commented on .github/workflows/linter.yml
> +      - master
Я прост ребейзнул миллион попыток починить линтер, поэтому вышло так..

2022-03-24 18:07 UTC, hackfeed commented on bongocli/Makefile
> +	rm -rf bin/*.exe
Уберу

2022-03-24 18:08 UTC, hackfeed commented on bongocli/cmd/bongocli/main.go
> +		errr := conn.Close()
Там идет [error shadowing](https://ixday.github.io/post/golang-err-shadowing/), поэтому нужна новая переменная ошибки

2022-03-24 18:08 UTC, hackfeed commented
> Так как мы не делаем squash в один коммит при мерджом, я бы вынес изменения gitignore, linter в другие коммиты.

Вроде как наоборот мы делаем squash

2022-03-24 18:18 UTC, mRrvz commented on bongocli/cmd/bongocli/main.go
> +		errr := conn.Close()
если я правильно понял, тогда логичнее назвать не errr, a error. или типа будет конфликтовать с типом error?

2022-03-24 18:19 UTC, mRrvz commented
тогда почему у нас при 5 прах в мастере 20 комитов

2022-03-24 18:19 UTC, hackfeed commented on bongocli/cmd/bongocli/main.go
> +		errr := conn.Close()
Да, будет конфликт. Обычно просто на каждый такой шадоу еррор докидывают еще одну r к err

2022-03-24 18:20 UTC, mRrvz commented on .github/workflows/linter.yml
> +      - master
ладно

2022-03-24 18:20 UTC, hackfeed commented
> тогда почему у нас при 5 прах в мастере 20 комитов

Потому что я джобы в мастере настраивал, я ж тебе говорил

2022-03-24 18:20 UTC, mRrvz commented on bongocli/cmd/bongocli/main.go
> +		errr := conn.Close()
ок

2022-03-24 18:22 UTC, mRrvz approved these changes
ладно, тут не критично, но в любом случае такие коммиты (разбитые) проще ревьювить

2022-03-24 18:29 UTC, Justarone approved these changes
SWAG

2022-03-24 18:30 UTC, merged