[GH-21] Реализовать SGDT в `bongocli`
iu7og/bongodb pull request #29
Opened 2022-03-26 10:41 UTC by hackfeed

* Add basic SGDT interface for CLI client

Closes GH-21

2022-03-26 13:38 UTC, Justarone requested changes

2022-03-26 13:38 UTC, Justarone commented on .gitignore
> +# Server stub for client testing
Это автогенерирующийся мок, поэтому ты его не включаешь?

2022-03-26 13:38 UTC, Justarone commented on bongocli/LICENSE
> +                    GNU GENERAL PUBLIC LICENSE
1. Мы хотим отдельную лицензию под каждый продукт?
2. Мы хотим лицензию?
3. Мы хотим лицензию в этом PR?

2022-03-26 13:38 UTC, Justarone commented on bongocli/cmd/connect.go
> +		r.Comma = ' '
не будет шизы с 2 пробелами? может просто сплит по whitespace'ам сделать, вместо какого-то csv.reader'a?

2022-03-26 13:38 UTC, Justarone commented on bongocli/cmd/connect.go
> +		}
по-моему можно заменить csv.Reader и вот эти танцы на `strings.Fields`

2022-03-26 13:38 UTC, Justarone commented on bongocli/cmd/connect.go
> +			_, err = c.Set(ctx, &bongodb.KeyValueRequest{
Давай `c` переименуем на что-нибудь более со смыслом (`connect`, `connectDescriptor` etc)

2022-03-26 13:38 UTC, Justarone commented on bongocli/cmd/connect.go
> +	r := csv.NewReader(strings.NewReader(input))
явно код дублируется, нужно как-то собрать в одно место (либо `string.Fields`)

2022-03-26 13:38 UTC, Justarone commented on bongocli/cmd/connect.go
> +	twoArgsCmds := map[string]struct{}{
немного опрометчиво
как это будет работать с json'о-подобными значениями?
`set Lexa "{\"bongo\": \"db\"}"`
или мы такое не допускаем?

2022-03-26 13:38 UTC, Justarone commented on bongocli/cmd/connect.go
> +	twoArgsCmds := map[string]struct{}{
И почему бы ваще не замаппить просто команды в количество аргументов?
ну то есть:
```go
    zeroArgsCmds := map[string]int{
		"truncate": 0,
		"exit": 0,
// ...
    }
```
тогда можно сразу проверить и наличие команды и нужное число аргументов (да, я экономлю строки, а то еще на бумаге заставят печатать)

2022-03-26 13:38 UTC, Justarone commented on bongocli/cmd/root.go
> +	cobra.OnInitialize(initConfig)
а что за конфиг и че он настраивает? коннект? это типа альтернатива аргументам командной строки?

2022-03-26 13:38 UTC, Justarone commented on bongocli/internal/connect/connect.go
> +	conn, err := grpc.Dial(addr, grpc.WithTransportCredentials(insecure.NewCredentials()))
а это планируется не oneshot? ну то есть подключился, пообщался, отключился...

2022-03-26 13:38 UTC, Justarone commented on bongocli/internal/connect/connect.go
> +	conn, err := grpc.Dial(addr, grpc.WithTransportCredentials(insecure.NewCredentials()))
(ну и в этом месте возможно еще что-то поменяется, все зависит от того ,че мы на сипипи слепим, но это еще обсудим, да.. выглядит так, что подключение лучше)

2022-03-26 16:45 UTC, hackfeed commented on .gitignore
> +# Server stub for client testing
Нет, это реализация, которую я набросал на коленке, чтобы проверить работоспособность

2022-03-26 16:45 UTC, hackfeed commented on bongocli/LICENSE
> +                    GNU GENERAL PUBLIC LICENSE
Это автоген от кобры, поэтому решил оставить

2022-03-26 16:46 UTC, hackfeed commented on bongocli/cmd/connect.go
> +		r.Comma = ' '
Нет, именно для того, чтобы решить шизу с двумя пробелами, юзается эта конструкция

2022-03-26 16:46 UTC, hackfeed commented on bongocli/cmd/connect.go
> +		}
Нет

2022-03-26 16:46 UTC, hackfeed commented on bongocli/cmd/connect.go
> +			_, err = c.Set(ctx, &bongodb.KeyValueRequest{
Хорошо

2022-03-26 16:46 UTC, hackfeed commented on bongocli/cmd/connect.go
> +	r := csv.NewReader(strings.NewReader(input))
Принято

2022-03-26 16:48 UTC, hackfeed commented on bongocli/cmd/connect.go
> +	twoArgsCmds := map[string]struct{}{
По поводу мапы там другая проверка немного, а не та, о которой ты думаешь (вроде). С жсонами шизы не будет

2022-03-26 16:48 UTC, hackfeed commented on bongocli/cmd/root.go
> +	cobra.OnInitialize(initConfig)
Это автоген

2022-03-26 16:48 UTC, hackfeed commented on bongocli/internal/connect/connect.go
> +	conn, err := grpc.Dial(addr, grpc.WithTransportCredentials(insecure.NewCredentials()))
Нет, не oneshot

2022-03-26 16:52 UTC, Justarone commented on bongocli/cmd/root.go
> +	cobra.OnInitialize(initConfig)
Понятнее не стало... Файл автоматом сгенерился?

2022-03-26 16:53 UTC, Justarone commented on bongocli/LICENSE
> +                    GNU GENERAL PUBLIC LICENSE
Когда в начале пишется, где автоген, а где нет - проще.. лишнее мог не смотреть..

2022-03-26 16:54 UTC, Justarone commented on bongocli/cmd/root.go
> +	cobra.OnInitialize(initConfig)
Оке, я понял, помечай как-нибудь такое что ли, чтобы мы не смотрели..

2022-03-26 17:04 UTC, Justarone commented on bongocli/cmd/connect.go
> +	twoArgsCmds := map[string]struct{}{
Окей, я короче понял, почему csv.reader (типа в строке пробелы он проигнорирует, так?), но по поводу мамы ты меня недопонял. Я предлагаю вместо switch по длине и просмотра разных мап примерно такое:
```go
map[string]int commandToArgs = { { "truncate", oneArg } ... };
argsAmount, ok = commandToArgs[cmdParts[0]];
```
И тогда если не ок - то такой команды нет, если `len(cmdParts) != argsAmount` - неверное количество аргументов.

2022-03-26 21:22 UTC, Justarone commented on .gitignore
> +# Server stub for client testing
я думаю, что стоит ее преобразовать так, что бы не стыдно было залить, и залить..

2022-03-27 08:56 UTC, hackfeed commented on .gitignore
> +# Server stub for client testing
Вообще не вижу смысла заливать заглушку для сервера

2022-03-27 08:58 UTC, Justarone submitted a review, later dismissed

2022-03-27 10:42 UTC, Justarone approved these changes

2022-03-27 11:24 UTC, mRrvz commented
почему в последнем коммите есть WIP?

2022-03-27 11:46 UTC, mRrvz requested changes

2022-03-27 11:46 UTC, mRrvz commented on bongocli/cmd/connect.go
> +	Long: `Connect to existent bongodb instance.
разницы между long и short description нет, как минимум по размеру...

2022-03-27 11:46 UTC, mRrvz commented on bongocli/cmd/connect.go
> +	Short: "Connect to bongodb server instance",
тут точки нет, а снизу есть

2022-03-27 11:46 UTC, mRrvz commented on bongocli/cmd/connect.go
> +		return fmt.Errorf("error while connecting to bongodb instance in connect command, error is: %v", err)
"error while connecting to bongodb instance in connect command: %v", err

2022-03-27 11:46 UTC, mRrvz commented on bongocli/cmd/connect.go
> +			return errors.New("invalid command")
а зачем это

2022-03-27 11:46 UTC, mRrvz commented on bongocli/cmd/connect.go
> +		}
в свитчах хорошо быть добавить default и высирать ошибку куда либо

2022-03-27 11:46 UTC, mRrvz commented on bongocli/cmd/connect.go
> +	switch cmd[0] {
мб strings.ToLower(cmd[0])?

получается у тебя тут функция незаметно подменяет элемент массива

2022-03-27 11:46 UTC, mRrvz commented on bongocli/cmd/root.go
> +		Long: `Client for interaction with bongodb.
тут получается что у шорт описание больше чем у лонг

2022-03-27 11:46 UTC, mRrvz commented on bongocli/main.go
> +func main() {
было бы неплохо тут поднять defer func ( ... recover ... )

2022-03-27 11:47 UTC, hackfeed commented on bongocli/cmd/connect.go
> +	Long: `Connect to existent bongodb instance.
Прочитай дальше строчку..

2022-03-27 11:49 UTC, hackfeed commented on bongocli/cmd/connect.go
> +	Short: "Connect to bongodb server instance",
Почитай полностью..

2022-03-27 11:49 UTC, hackfeed commented on bongocli/cmd/connect.go
> +		return fmt.Errorf("error while connecting to bongodb instance in connect command, error is: %v", err)
Думаешь?

2022-03-27 11:49 UTC, hackfeed commented on bongocli/cmd/connect.go
> +			return errors.New("invalid command")
Для валидации внутри команды при вводе неверной команды

2022-03-27 11:50 UTC, hackfeed commented on bongocli/cmd/connect.go
> +		}
Кк

2022-03-27 11:50 UTC, hackfeed commented on bongocli/cmd/connect.go
> +	switch cmd[0] {
Справедливо

2022-03-27 11:50 UTC, hackfeed commented on bongocli/cmd/root.go
> +		Long: `Client for interaction with bongodb.
Там дальше строчка епт братанчик

2022-03-27 11:50 UTC, hackfeed commented on bongocli/main.go
> +func main() {
Это кобра генерит, она умно генерит..

2022-03-27 14:00 UTC, mRrvz approved these changes
апрув братишка..

2022-03-27 14:02 UTC, merged