[GH-4] Настроить линтер
iu7og/bongodb pull request #5
Opened 2022-02-21 19:44 UTC by hackfeed

* Настроен линтер
* Внесены изменения в README
* Внесены изменения в .gitignore

Closes GH-4

2022-02-21 20:04 UTC, mRrvz requested changes
Если у нас squash & merge - где то (я думаю в описании пулл реквеста), нужно написать коммит месейдж (по факту у тебя сейчас это есть, но на русском, но коммиты у нас на английском). Я бы просто описание пулл реквеста писал по-английски, но на самом деле мне всё равно

2022-02-22 08:32 UTC, hackfeed commented
> Если у нас squash & merge - где то (я думаю в описании пулл реквеста), нужно написать коммит месейдж (по факту у тебя сейчас это есть, но на русском, но коммиты у нас на английском). Я бы просто описание пулл реквеста писал по-английски, но на самом деле мне всё равно

Хорошо, давайте описание пулл реквеста писать по-английски

2022-02-22 11:50 UTC, mRrvz commented
Давайте в комментах которые исправлены писать "пофиксил" или типа того (тот кто фиксит), но кнопку resolve будет жать тот, кто коммент оставил

2022-02-22 13:27 UTC, hackfeed commented on .github/workflows/linter.yml
> +          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
Пофиксил

2022-02-22 13:27 UTC, hackfeed commented on .gitignore
> +.DS_Store
Пофиксил

2022-02-24 11:39 UTC, mRrvz submitted a review, later dismissed
LGTM

2022-02-24 12:22 UTC, mRrvz commented on .github/workflows/branch.yml
> +          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
получается если пулл реквест будет закрыт не при мердже, а просто кнопкой, то ветка тоже удалиться?

2022-02-24 12:23 UTC, hackfeed commented on .github/workflows/branch.yml
> +          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
Нет, там для этого есть флаг, который по умолчанию в false, его указывать не надо, он не даст удалить ветку если просто закрыт был

2022-02-24 12:23 UTC, TheSawIsTheLaw approved these changes
LGTM

2022-02-24 12:25 UTC, mRrvz commented on .github/workflows/branch.yml
> +          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
харош красава

2022-02-24 12:26 UTC, mRrvz approved these changes

2022-02-24 12:28 UTC, merged